trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: PROD
    dependsOn: []
    jobs:
      - job: JOB_PROD

  - stage: TEST
    jobs:
      - job: JOB_TEST
    
  - stage: DEPOLY
    dependsOn: []
    jobs:
      - job: JOB_DEPOLY

