trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: PROD
    jobs:
      - job: JOB_PROD

  - stage: TEST
    dependsOn: PROD
    jobs:
      - job: JOB_TEST
  - stage: TEST2
    dependsOn: PROD
    jobs:
      - job: job_test2

  - stage: DEPOLY
    dependsOn: 
     - TEST
     - TEST2
    jobs:
      - job: JOB_DEPOLY

